@startuml
start
:Пользователь нажимает "Оформить заказ";
:Проверить наличие товара;
if (товар в наличии?) then (да)
:Зарезервировать товар;
:Создать заказ;
:Отправить письмо клиенту;
:Уведомить менеджера;
:Перенаправить на страницу успеха;
else (нет)
:Отправить уведомление об отсутствии;
:Предложить аналоги;
:Вернуть в корзину;
endif
stop
@enduml